# Select image from https://hub.docker.com/r/_/php/
image: php:7.2

cache:
  paths:
    - vendor/

before_script:
# Install dependencies
- bash ci/docker_install.sh > /dev/null
# Install Xdebug
- pecl install xdebug
# Enable Xdebug
- docker-php-ext-enable xdebug
# Install composer
- curl -sS https://getcomposer.org/installer | php
- php composer.phar install

test:app:
  script:
  - phpunit --configuration tests/phpunit.xml

coverage:
  stage: test
  script:
    - ./vendor/bin/phpunit --configuration ./tests/phpunit.xml --coverage-html coverage/ ./tests/
  artifacts:
    paths:
      - coverage/


pages:
  stage: deploy
  dependencies:
    - coverage
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
  only:
      - master