# Select image from https://hub.docker.com/r/_/php/
image: php:7.2

cache:
  paths:
    - vendor/

services:
  - mysql:5.7

variables:
  MYSQL_DATABASE: citest
  MYSQL_ROOT_PASSWORD: 1234

before_script:
# Install dependencies
- bash ci/docker_install.sh > /dev/null
# Install Xdebug
- pecl install xdebug
# Enable Xdebug
- docker-php-ext-enable xdebug
- docker-php-ext-install mysqli
- docker-php-ext-enable mysqli
# Install composer
- curl -sS https://getcomposer.org/installer | php
- php composer.phar install

connect:
  stage: build 
  image: mysql
  script:
  - mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql "$MYSQL_DATABASE" < db.sql

test:app:
  script:
  - phpunit --configuration tests/phpunit.xml

coverage:
  stage: test
  dependencies:
    - connect
  script:
    - vendor/bin/phpunit --configuration tests/phpunit.xml --coverage-html coverage/ tests/
  artifacts:
    paths:
      - coverage/


pages:
  stage: deploy
  dependencies:
    - coverage
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
  only:
      - master